version: "3.3"

services:
  database:
    image: postgres
    container_name: database
    ports:
    - 5432:5432
    environment:
      - POSTGRES_DB=trading_view_test
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
  migrations:
    build: .
    container_name: migrations
    working_dir: /app/
    command: python backend/manage.py migrate
    volumes:
      - .:/app/
    depends_on:
      - database
  web:
    build: .
    container_name: web
    restart: unless-stopped
    working_dir: /app/
    command: python backend/manage.py runserver 0.0.0.0:80
    volumes:
    - .:/app/
    ports:
    - 80:80
    depends_on:
      - database
      - migrations
