# Generated by Django 3.2.8 on 2021-10-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.CharField(blank=True, max_length=67),
        ),
    ]
